### ISSUE TITLE
MAJOR SOUNDCLOUD API CHANGE

### ISSUE THREAD

**Issue by lesterrry** [lesterrry/Radio-Automne#42]
I encountered it while quick boot was set to 0

**Comment by Lesterrry** [comment]
Something is wrong with the api, maybe it declines my key or something

**Comment by Lesterrry** [comment]
Holy fuck there idiots decided to change their api and everything is falling apart now wow what a miracle

**Comment by lesterrry** [comment]
[Solved](https://github.com/lesterrry/autumn-bird) :)
